version: '3.1'

services:

  nginxproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 8002:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

    # portainer reset password
    # docker container stop portainer
    # docker run --rm -v portainer_data:/data portainer/helper-reset-password

  webssh2:
    container_name: webssh2
    image: billchurch/webssh2
    ports:
      - 8001:2222

  












  # dummy:
  #   container_name: dummy
  #   build: 
  #     context: ./docker
  #     dockerfile: Dockerfile
  #     args:
  #       org: rasa train --data data/chitchat/nlu.yml data/evis/nlu.yml data/chitchat/rules.yml data/evis/rules.yml data/chitchat/stories.yml data/evis/stories.yml -d data/evis/domain --config data/evis/config.yml
  #   ports:
  #     - "1002:5005"
  #   command: rasa run --enable-api --log-file rasa.log --debug --cors "*"


  # evis:
  #  container_name: evis
  #  image: rasa-faq:latest
  #  ports:
  #    - "5005:5005"
  #  restart: always
  #  command: rasa run -m models/evis-model.tar.gz --enable-api  --log-file rasa.log --debug --cors "*"

  # organization:
  #   container_name: organization
  #   image: rasa-faq:latest
  #   ports:
  #     - "5000:5005"
  #   restart: always
  #   command: rasa run -m models/organization-model.tar.gz --enable-api  --log-file rasa.log --debug --cors "*"

# networks:
#   code-network:
#     driver: bridge

    # networks:
    #   - code-network
