version: '3.1'

services:

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 8002:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

    # portainer reset password
    # docker container stop portainer
    # docker run --rm -v portainer_data:/data portainer/helper-reset-password

  webssh2:
    container_name: webssh2
    image: billchurch/webssh2
    ports:
      - 8001:2222
